---
version: '2'
services:
  app:
    environment:
      - DOCKER_PYR_PG_HOST=db
    image: phoenix:1.4.0
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    depends_on:
      - db
  db:
    image: mdillon/postgis:9.6
